S = RECORD (<EOL> RECORD)* (<EOL> PARTIAL_RECORD)? <EOL>?
RECORD = FIELD (<COMMA> FIELD)*
PARTIAL_RECORD = (FIELD <COMMA>)* PARTIAL_FIELD
FIELD = ESCAPED | NON_ESCAPED
PARTIAL_FIELD = PARTIAL_ESCAPED | NON_ESCAPED
PARTIAL_ESCAPED = <DQUOTE> (TEXTDATA | <EOL> | <COMMA> | ESCAPED_DQUOTE )*
<ESCAPED> = <DQUOTE> (TEXTDATA | <EOL> | <COMMA> | ESCAPED_DQUOTE )* <DQUOTE>
<NON_ESCAPED> = TEXTDATA*
COMMA = #","
DQUOTE = #'"'
ESCAPED_DQUOTE = #'""'
TEXTDATA = #'[^,\r\n"]+'
EOL = #"(?:\r\n|\r|\n)"
